language: java
jdk:
  - oraclejdk8
env: 
  JAVA_OPTS: -Dspring.profiles.active=cloud
sudo: false
  mvn test
services:
  - postgresql
before_script:
  - psql -c 'create database Employee;' -U postgres
deploy:
  edge: true
  provider: cloudfoundry
  username: emails4suji@gmail.com
  password: "god@1234"
  api: https://api.run.pivotal.io
  organization: cloud_apps_suji.org
  space: sample_progs
before_install:
  - chmod +x mvnw
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V